name: Bug Report
description: Create a report about something that is not working
body:
- type: textarea
  attributes:
    label: Description
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To reproduce
    description: |
      Steps to reproduce the behavior:
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false
- type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Development
        - Non-Production
        - Production
  validations:
    required: false
- type: input
  attributes:
    label: App/Module
    description: In which app or module did the error occur?
  validations:
    required: false
- type: input
  attributes:
    label: URL
    description: Paste the URL of the website here.
  validations:
    required: false
- type: textarea
  attributes:
    label: Remarks
    description: Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
