name: Bug Report
description: Create a report about something that is not working
body:
- type: markdown
  attributes:
    value: |
      ## Bug Information
      Please provide a clear and concise description of the error and attach screenshots if helpful:
- type: textarea
  id: description
  attributes:
    label: Description
  validations:
    required: true
- type: textarea
  id: behaviour
  attributes:
    label: Expected behavior
  validations:
    required: false
- type: textarea
  id: steps
  attributes:
    label: Steps to reproduce
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      ## System Information
      Please give some information where the bug occurred:
- type: dropdown
  id: environment
  attributes:
    label: Environment
    options:
      - Development
      - Non-Production
      - Production
  validations:
    required: false
- type: input
  id: module
  attributes:
    label: Module
  validations:
    required: false
- type: input
  id: url
  attributes:
    label: URL
    description: Paste complete URL here
  validations:
    required: false
- type: dropdown
  id: client
  attributes:
    label: Client
    options:
      - Chrome
      - Edge
      - Firefox
      - Safari
      - iOS-App
      - Android-App
  validations:
    required: false
- type: input
  id: user
  attributes:
    label: User
    description: Logged in user account
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      ## Addition Information
      Is there anything else you want to mention or that will give more context about the issue:
- type: textarea
  id: remarks
  attributes:
    label: Remarks
  validations:
    required: false
