name: User Story
description: Create a user story to define a requirement to be implemented
body:
  - type: markdown
    attributes:
      value: Please enter a descriptive title and in the following provide a clear and concise description of the requirement.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the user story in one sentence.
      placeholder: As [role] I want to [do something] to [reach a specific goal].
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: These criteria must be met for the user story to be accepted as done.
      placeholder: |
        Please list fields, options and actions provided to the enduser and how the system should react.
        - The user can enter login the user name and password in separate fields.
        - The password field hides the entered characters.
        - After the button "Login" is clicked the system checks the given credentials.
        - On success the user is logged in and redirected to the dashboard, otherwise an invalid credentials error message is shown.
    validations:
      required: true
  - type: textarea
    id: usm-reference
    attributes:
      label: User journey map
      description: If applicable, please provide a reference to the related processes/steps in the User Journey Map.
      placeholder: |
        [Process]: [Step number], [Step number], ...
        [Process]: [Step number], ...
    validations:
      required: false
